### ISSUE TITLE
ImportError: cannot import name

### ISSUE THREAD

**Issue by silverbucket** [QUIC-Tracker/web-app#2]
I am setting up the docker image on a shared system behind a reverse proxy and would like to add a URL_PREFIX environ variable so all of the web-app URLs work within a `quic-tracker/` URI path.

I was preparing a PR but haven't been able to get the local web-app to run on my dev environment (though I've developed several flask apps I've never run into this problem). 

Adding a new class to `utils` I am unable to import it, actually I'm unable to import anything I've tried to add to the utils file, nor any file, whether variable, function or class. 

```
$ git diff quic_tracker/app.py
diff --git a/quic_tracker/app.py b/quic_tracker/app.py
index c84f257..8e263cf 100644
--- a/quic_tracker/app.py
+++ b/quic_tracker/app.py
@@ -26,10 +26,14 @@ from flask.templating import render_template

 from quic_tracker.traces import get_traces, parse_trace, find_similar_trace_idx
 from quic_tracker.utils import find_latest_file, ByteArrayEncoder, is_tuple, decode, join_root, find_data_files, \
-    find_previous_file, find_next_file
+    find_previous_file, find_next_file, UrlPrefixMiddleware

 app = Flask(__name__)
 app.json_encoder = ByteArrayEncoder
$ git diff quic_tracker/utils.py
diff --git a/quic_tracker/utils.py b/quic_tracker/utils.py
index ac284df..ea480e0 100644
--- a/quic_tracker/utils.py
+++ b/quic_tracker/utils.py
@@ -62,3 +62,20 @@ def split_every_n(string, n=2):
 def decode(hex_byte):
     c = chr(int('0x' + hex_byte, base=16))
     return c if c.isprintable() else '.'
+
+
+class UrlPrefixMiddleware(object):
+    pass
$ venv/bin/python3 quic_tracker/app.py
Traceback (most recent call last):
  File "quic_tracker/app.py", line 28, in <module>
    from quic_tracker.utils import find_latest_file, ByteArrayEncoder, is_tuple, \
ImportError: cannot import name 'UrlPrefixMiddleware' from 'quic_tracker.utils' (/Users/njenning/code/devqa/quic-tracker-web-app/venv/lib/python3.8/site-packages/quic_tracker/utils.py)
```

Sorry If I'm missing something totally obvious, but I've not been able to find any similar situation searching for the error message, and it's rather general. Is there something about the setup of this app that I might have overlooked that could be causing this? 

It's worth noting I've tried with both `python3.6` and `python3.8`

**Comment by mpiraux** [comment]
The feature you describe looks useful indeed. Your PR is welcome once it's ready :)

> ImportError: cannot import name 'UrlPrefixMiddleware' from 'quic_tracker.utils' (/Users/njenning/code/devqa/quic-tracker-web-app/venv/lib/python3.8/site-packages/quic_tracker/utils.py)

Could this be a conflict between a version that you pip installed and your local working copy of the app ? If you only have one copy, i.e. in the site-packages/quic_tracker dir, then that's really obscure to me.

**Comment by silverbucket** [comment]
@mpiraux I see, I'm wondering how you normally do your development work with this web app then? Normally I use the files in the local branch for development with just the dependencies in the venv. However in this case they seem to be installed during the pip installation from the git url, and completely ignore the local files.

**Comment by mpiraux** [comment]
I guess I installed every package manually when building the web-app and never had to reinstall the dependencies only. Apparently this common use case is not very cleanly addressed by pip: https://stackoverflow.com/questions/30797124/how-to-use-setup-py-to-install-dependencies-only. Uninstalling the package right after should leave you with just the dependencies.
